AWSTemplateFormatVersion: "2010-09-09"
Description: CloudFormation template to create a API Gateway

Parameters:
  ApiGatewayName:
    Type: String
    Description: API Gateway name
  CognitoStack:
    Type: String
    Description: stack name

Resources:
  ApiGateway:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: !Ref ApiGatewayName

  ApiGatewayAuthorizer:
    Type: AWS::ApiGateway::Authorizer
    Properties:
      Name: CognitoAuthorizer
      Type: COGNITO_USER_POOLS
      RestApiId: !Ref ApiGateway
      IdentitySource: method.request.header.Authorization
      ProviderARNs:
        - Fn::ImportValue: !Sub "${CognitoStack}-CognitoUserPoolArn"

Outputs:
  ApiEndpoint:
    Description: The endpoint URL for the API
    Value: !Sub "https://${ApiGateway}.execute-api.${AWS::Region}.amazonaws.com/prod/myresource"
  ApiGatewayRootResourceId:
    Description: Root resource of API Gateway
    Value: !GetAtt ApiGateway.RootResourceId
  ApiGatewayRestApiId:
    Description: REST API of API Gateway
    Value: !GetAtt ApiGateway.RestApiId
