AWSTemplateFormatVersion: "2010-09-09"
Description: CloudFormation template to create a CloudFront distribution.

Parameters:
  S3StaticWebsiteStack:
    Type: String
    Description: stack name
  CertificateArn:
    Type: String
    Description: ACM Certificate ARN

Resources:
  MyLoggingBucket:
    Type: AWS::S3::Bucket
    Properties:
      OwnershipControls:
        Rules:
          - ObjectOwnership: BucketOwnerPreferred

  # Use CustomOriginConfig for S3 Bucket static website hosting
  # https://docs.aws.amazon.com/cloudfront/latest/APIReference/API_CustomOriginConfig.html
  # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/quickref-cloudfront.html#scenario-cloudfront-customorigin

  MyCFDistribution:
    Type: "AWS::CloudFront::Distribution"
    Properties:
      DistributionConfig:
        Origins:
          - DomainName:
              Fn::ImportValue: !Sub "${S3StaticWebsiteStack}-DomainName"
            Id: S3OriginId
            CustomOriginConfig:
              HTTPPort: 80
              HTTPSPort: 443
              OriginProtocolPolicy: http-only
              OriginSSLProtocols:
                - TLSv1.2
                - TLSv1.1
        Enabled: "true"
        Comment: MY CloudFront distribution
        DefaultRootObject: index.html
        Logging:
          IncludeCookies: "false"
          Bucket: !GetAtt MyLoggingBucket.DomainName
          Prefix: cloudfront
        Aliases:
          - Fn::ImportValue: !Sub "${S3StaticWebsiteStack}-S3BucketName"
        DefaultCacheBehavior:
          Compress: "true"
          AllowedMethods:
            - DELETE
            - GET
            - HEAD
            - OPTIONS
            - PATCH
            - POST
            - PUT
          TargetOriginId: S3OriginId
          CachePolicyId: "658327ea-f89d-4fab-a63d-7e88639e58f6"
          OriginRequestPolicyId: "88a5eaf4-2fd4-4709-b370-b4c650ea3fcf"
          ViewerProtocolPolicy: redirect-to-https
        PriceClass: PriceClass_200
        ViewerCertificate:
          AcmCertificateArn: !Ref CertificateArn
          SslSupportMethod: sni-only
          MinimumProtocolVersion: TLSv1

Outputs:
  MyCFDistributionId:
    Value: !GetAtt MyCFDistribution.Id
    Description: Id of CloudFront distribution
    Export:
      Name:
        Fn::Sub: "${AWS::StackName}-MyCFDistributionId"
  MyCFDistributionDomainName:
    Value: !GetAtt MyCFDistribution.DomainName
    Description: Domain name of CloudFront distribution
    Export:
      Name:
        Fn::Sub: "${AWS::StackName}-MyCFDistributionDomainName"
