AWSTemplateFormatVersion: "2010-09-09"
Description: CloudFormation template to create a CloudFront distribution.

Parameters:
  S3StaticWebsiteStack:
    Type: String
    Description: stack name
  Route53DNSStack:
    Type: String
    Description: stack name
  CertificateArn:
    Type: String
    Description: ACM Certificate ARN
  CloudFrontHostedZone:
    Type: String
    Description: https://docs.aws.amazon.com/general/latest/gr/cf_region.html#cf_region

Resources:
  MyLoggingBucket:
    Type: AWS::S3::Bucket
    Properties:
      OwnershipControls:
        Rules:
          - ObjectOwnership: BucketOwnerPreferred

  # Use CustomOriginConfig for S3 Bucket static website hosting
  # https://docs.aws.amazon.com/cloudfront/latest/APIReference/API_CustomOriginConfig.html
  # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/quickref-cloudfront.html#scenario-cloudfront-customorigin

  MyCFDistribution:
    Type: "AWS::CloudFront::Distribution"
    Properties:
      DistributionConfig:
        Origins:
          - DomainName:
              Fn::ImportValue: !Sub "${S3StaticWebsiteStack}-DomainName"
            Id: S3OriginId
            CustomOriginConfig:
              HTTPPort: 80
              HTTPSPort: 443
              OriginProtocolPolicy: http-only
              OriginSSLProtocols:
                - TLSv1.2
                - TLSv1.1
        Enabled: "true"
        Comment: MY CloudFront distribution
        DefaultRootObject: index.html
        Logging:
          IncludeCookies: "false"
          Bucket: !GetAtt MyLoggingBucket.DomainName
          Prefix: cloudfront
        Aliases:
          - Fn::ImportValue: !Sub "${S3StaticWebsiteStack}-S3BucketName"
        DefaultCacheBehavior:
          Compress: "true"
          AllowedMethods:
            - DELETE
            - GET
            - HEAD
            - OPTIONS
            - PATCH
            - POST
            - PUT
          TargetOriginId: S3OriginId
          CachePolicyId: "658327ea-f89d-4fab-a63d-7e88639e58f6"
          OriginRequestPolicyId: "88a5eaf4-2fd4-4709-b370-b4c650ea3fcf"
          ViewerProtocolPolicy: redirect-to-https
        PriceClass: PriceClass_200
        ViewerCertificate:
          AcmCertificateArn: !Ref CertificateArn
          SslSupportMethod: sni-only
          MinimumProtocolVersion: TLSv1
        CustomErrorResponses:
          - ErrorCode: 404
            ResponseCode: 200
            ResponsePagePath: /index.html
            ErrorCachingMinTTL: 0
          - ErrorCode: 403
            ResponseCode: 200
            ResponsePagePath: /index.html
            ErrorCachingMinTTL: 0

  # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-route53-recordset-aliastarget.html

  WebAppRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId:
        Fn::ImportValue: !Sub "${Route53DNSStack}-HostedZoneId"
      Name:
        Fn::ImportValue: !Sub "${Route53DNSStack}-AppDomainName"
      Type: A
      AliasTarget:
        HostedZoneId: !Ref CloudFrontHostedZone
        DNSName: !GetAtt MyCFDistribution.DomainName
        EvaluateTargetHealth: false

Outputs:
  MyCFDistributionId:
    Value: !GetAtt MyCFDistribution.Id
    Description: Id of CloudFront distribution
    Export:
      Name:
        Fn::Sub: "${AWS::StackName}-MyCFDistributionId"
  MyCFDistributionDomainName:
    Value: !GetAtt MyCFDistribution.DomainName
    Description: Domain name of CloudFront distribution
    Export:
      Name:
        Fn::Sub: "${AWS::StackName}-MyCFDistributionDomainName"
  S3BucketName:
    Value:
      Fn::Select:
        - 0
        - Fn::Split: [".s3.amazonaws.com", !GetAtt MyLoggingBucket.DomainName]
