AWSTemplateFormatVersion: "2010-09-09"
Description: CloudFormation template to create a Amazon Cognito User Pool

Parameters:
  ClientAppDomainName:
    Type: String
    Description: User Pool client app domain name

Resources:
  CognitoUserPool:
    Type: AWS::Cognito::UserPool
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      UserPoolName: EasyShopUserPool
      Policies:
        PasswordPolicy:
          MinimumLength: 8
          RequireUppercase: true
          RequireLowercase: true
          RequireNumbers: true
          RequireSymbols: false
      AutoVerifiedAttributes:
        - email
      Schema:
        - Name: email
          AttributeDataType: String
          Required: true
          Mutable: true
      AdminCreateUserConfig:
        AllowAdminCreateUserOnly: false
      AccountRecoverySetting:
        RecoveryMechanisms:
          - Priority: 1
            Name: verified_email

  CognitoUserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      UserPoolId: !Ref CognitoUserPool
      ClientName: EasyShopApp
      GenerateSecret: true
      ExplicitAuthFlows:
        - ALLOW_USER_SRP_AUTH
        - ALLOW_REFRESH_TOKEN_AUTH
      AllowedOAuthFlows:
        - implicit
      AllowedOAuthScopes:
        - email
        - openid
        - profile
      CallbackURLs:
        - https://oauth.pstmn.io/v1/callback
        - !Sub "https://${ClientAppDomainName}/callback"
      LogoutURLs:
        - !Sub "https://${ClientAppDomainName}/logout"

Outputs:
  CognitoUserPoolId:
    Description: ID of the Cognito User Pool
    Value: !GetAtt CognitoUserPool.UserPoolId
    Export:
      Name:
        Fn::Sub: "${AWS::StackName}-CognitoUserPoolId"
  CognitoUserPoolProviderName:
    Description: Provider of the Cognito User Pool
    Value: !GetAtt CognitoUserPool.ProviderName
    Export:
      Name:
        Fn::Sub: "${AWS::StackName}-CognitoUserPoolProviderName"
  CognitoUserPoolProviderUrl:
    Description: Provider URL of the Cognito User Pool
    Value: !GetAtt CognitoUserPool.ProviderURL
    Export:
      Name:
        Fn::Sub: "${AWS::StackName}-CognitoUserPoolProviderUrl"
  CognitoUserPoolClientId:
    Description: ID of the Cognito User Pool Client
    Value: !GetAtt CognitoUserPoolClient.ClientId
    Export:
      Name:
        Fn::Sub: "${AWS::StackName}-CognitoUserPoolClientId"
  CognitoUserPoolClientSecret:
    Description: Secret of the Cognito User Pool Client
    Value: !GetAtt CognitoUserPoolClient.ClientSecret
    Export:
      Name:
        Fn::Sub: "${AWS::StackName}-CognitoUserPoolClientSecret"
