AWSTemplateFormatVersion: "2010-09-09"
Description: CloudFormation template to create a Amazon Cognito User Pool

Parameters:
  ClientAppDomainName:
    Type: String
    Description: User Pool client app domain name

Resources:
  ###############################################
  # Cognito UserPool
  ###############################################

  CognitoUserPool:
    Type: AWS::Cognito::UserPool
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      UserPoolName: EasyShopUserPool
      Policies:
        PasswordPolicy:
          MinimumLength: 8
          RequireUppercase: true
          RequireLowercase: true
          RequireNumbers: true
          RequireSymbols: false
      AutoVerifiedAttributes:
        - email
      Schema:
        - Name: email
          AttributeDataType: String
          Required: true
          Mutable: true
      AdminCreateUserConfig:
        AllowAdminCreateUserOnly: false
      AccountRecoverySetting:
        RecoveryMechanisms:
          - Priority: 1
            Name: verified_email

  # https://docs.aws.amazon.com/cognito/latest/developerguide/user-pool-settings-client-apps.html

  CognitoUserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      UserPoolId: !Ref CognitoUserPool
      ClientName: EasyShopApp
      GenerateSecret: true
      ExplicitAuthFlows:
        - ALLOW_USER_SRP_AUTH
        - ALLOW_USER_PASSWORD_AUTH
        - ALLOW_REFRESH_TOKEN_AUTH
      AllowedOAuthFlows:
        - implicit
      AllowedOAuthScopes:
        - email
        - openid
        - profile
        - aws.cognito.signin.user.admin
      CallbackURLs:
        - https://oauth.pstmn.io/v1/callback
        - !Sub "https://${ClientAppDomainName}/callback"
      LogoutURLs:
        - !Sub "https://${ClientAppDomainName}/logout"

  ###############################################
  # Cognito Groups & Users
  ###############################################

  CognitoCustomerGroup:
    Type: AWS::Cognito::UserPoolGroup
    Properties:
      Description: "EasyShop customer group"
      GroupName: "customer"
      UserPoolId: !Ref CognitoUserPool

  CognitoAdminGroup:
    Type: AWS::Cognito::UserPoolGroup
    Properties:
      Description: "EasyShop admin group"
      GroupName: "admin"
      UserPoolId: !Ref CognitoUserPool

  CognitoAdmin1User:
    Type: AWS::Cognito::UserPoolUser
    Properties:
      UserPoolId: !Ref CognitoUserPool
      Username: admin01.grp6asm3@yopmail.com
      UserAttributes:
        - Name: email
          Value: admin01.grp6asm3@yopmail.com

  CognitoAdmin2User:
    Type: AWS::Cognito::UserPoolUser
    Properties:
      UserPoolId: !Ref CognitoUserPool
      Username: admin02.grp6asm3@yopmail.com
      UserAttributes:
        - Name: email
          Value: admin02.grp6asm3@yopmail.com

  AddAdmin1UserToGroup:
    Type: AWS::Cognito::UserPoolUserToGroupAttachment
    Properties:
      UserPoolId: !Ref CognitoUserPool
      GroupName: !Ref CognitoAdminGroup
      Username: !Ref CognitoAdmin1User

  AddAdmin2UserToGroup:
    Type: AWS::Cognito::UserPoolUserToGroupAttachment
    Properties:
      UserPoolId: !Ref CognitoUserPool
      GroupName: !Ref CognitoAdminGroup
      Username: !Ref CognitoAdmin2User

Outputs:
  CognitoUserPoolArn:
    Description: ID of the Cognito User Pool
    Value: !GetAtt CognitoUserPool.Arn
    Export:
      Name:
        Fn::Sub: "${AWS::StackName}-CognitoUserPoolArn"
  CognitoUserPoolId:
    Description: ID of the Cognito User Pool
    Value: !GetAtt CognitoUserPool.UserPoolId
    Export:
      Name:
        Fn::Sub: "${AWS::StackName}-CognitoUserPoolId"
  CognitoUserPoolProviderName:
    Description: Provider of the Cognito User Pool
    Value: !GetAtt CognitoUserPool.ProviderName
    Export:
      Name:
        Fn::Sub: "${AWS::StackName}-CognitoUserPoolProviderName"
  CognitoUserPoolProviderUrl:
    Description: Provider URL of the Cognito User Pool
    Value: !GetAtt CognitoUserPool.ProviderURL
    Export:
      Name:
        Fn::Sub: "${AWS::StackName}-CognitoUserPoolProviderUrl"
  CognitoUserPoolClientId:
    Description: ID of the Cognito User Pool Client
    Value: !GetAtt CognitoUserPoolClient.ClientId
    Export:
      Name:
        Fn::Sub: "${AWS::StackName}-CognitoUserPoolClientId"
  CognitoUserPoolClientSecret:
    Description: Secret of the Cognito User Pool Client
    Value: !GetAtt CognitoUserPoolClient.ClientSecret
    Export:
      Name:
        Fn::Sub: "${AWS::StackName}-CognitoUserPoolClientSecret"
