AWSTemplateFormatVersion: "2010-09-09"
Description: CloudFormation template to create a Route53.

Parameters:
  RootDomainName:
    Type: String
    Description: Root domain name
  DomainName:
    Type: String
    Description: Route53 domain name
  S3WebsiteHostedZoneId:
    Type: String
    Description: Amazon S3 website HostedZone IDs (refer to Amazon Reference guide)
  S3WebsiteEndpoint:
    Type: String
    Description: Amazon S3 website endpoints (refer to Amazon Reference guide)

Resources:
  DNS:
    Type: "AWS::Route53::HostedZone"
    Properties:
      HostedZoneConfig:
        Comment: !Sub "Hosted zone for ${DomainName}"
      Name: !Ref DomainName
      HostedZoneTags:
        - Key: "Purpose"
          Value: "Asm3"

  WebAppRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref DNS
      Name: !Sub "app.${DomainName}"
      Type: A
      AliasTarget:
        HostedZoneId: !Ref S3WebsiteHostedZoneId
        DNSName: !Ref S3WebsiteEndpoint

Outputs:
  RootDomainName:
    Value: !Ref RootDomainName
    Description: Root domain name
    Export:
      Name:
        Fn::Sub: "${AWS::StackName}-RootDomainName"
  WildcardRootDomainName:
    Value: !Sub "*.${RootDomainName}"
    Description: Wildcard Root domain name
    Export:
      Name:
        Fn::Sub: "${AWS::StackName}-WildcardRootDomainName"
  HostedZoneId:
    Value: !GetAtt DNS.Id
    Description: HostedZone ID
    Export:
      Name:
        Fn::Sub: "${AWS::StackName}-HostedZoneId"
  DomainName:
    Value: !Ref DomainName
    Description: HostedZone domain name
    Export:
      Name:
        Fn::Sub: "${AWS::StackName}-DomainName"
  WildcardDomainName:
    Value: !Sub "*.${DomainName}"
    Description: Wildcard HostedZone domain name
    Export:
      Name:
        Fn::Sub: "${AWS::StackName}-WildcardDomainName"
  NameServers:
    Value:
      Fn::Join:
        - ","
        - !GetAtt DNS.NameServers
    Description: URL for a static website hosted on S3
