AWSTemplateFormatVersion: "2010-09-09"
Description: CloudFormation template to create a free-tier EC2 instance, VPC, and Security Group.

Parameters:
  DomainName:
    Type: String
    Description: route53 domain name
  S3StaticWebsiteStack:
    Type: String
    Description: name of s3-static-website stack

Resources:
  DNS:
    Type: "AWS::Route53::HostedZone"
    Properties:
      HostedZoneConfig:
        Comment: !Sub "Hosted zone for ${DomainName}"
      Name: !Ref DomainName
      HostedZoneTags:
        - Key: "Purpose"
          Value: "Asm3"

Outputs:
  WebsiteURL:
    Value:
      Fn::Join:
        - ","
        - !GetAtt DNS.NameServers
    Description: URL for a static website hosted on S3
