AWSTemplateFormatVersion: "2010-09-09"
Description: CloudFormation template to create a S3 Bucket host a static website.

Parameters:
  StaticWebsiteBucketName:
    Type: String
    Description: name of S3 bucket

Resources:
  StaticWebsiteBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref StaticWebsiteBucketName
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: false
        IgnorePublicAcls: true
        RestrictPublicBuckets: false
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html
      CorsConfiguration:
        CorsRules:
          - AllowedHeaders:
              - "*"
            AllowedMethods:
              - GET
            AllowedOrigins:
              - "*"
            ExposedHeaders:
              - Date
            Id: myCORSRuleId1
            MaxAge: 3600
      Tags:
        - Key: "Purpose"
          Value: "Test"
        - Key: "Name"
          Value: "static-website-bucket"

  S3BucketPolicy:
    Type: "AWS::S3::BucketPolicy"
    Properties:
      Bucket: !Ref StaticWebsiteBucket
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Action:
              - "s3:GetObject"
            Effect: Allow
            Principal: "*"
            Resource: !Sub "arn:${AWS::Partition}:s3:::${StaticWebsiteBucket}/*"

Outputs:
  S3BucketWebsiteURL:
    Value: !GetAtt StaticWebsiteBucket.WebsiteURL
    Description: URL for a static website hosted on S3
    Export:
      Name:
        Fn::Sub: "${AWS::StackName}-S3BucketWebsiteURL"
  S3BucketDomaiName:
    Value: !GetAtt StaticWebsiteBucket.DomainName
    Description: URL for a static website hosted on S3
    Export:
      Name:
        Fn::Sub: "${AWS::StackName}-DomainName"
  S3BucketRegionalDomainName:
    Value: !GetAtt StaticWebsiteBucket.RegionalDomainName
    Description: URL for a static website hosted on S3
    Export:
      Name:
        Fn::Sub: "${AWS::StackName}-S3BucketRegionalDomainName"
  S3BucketSecureURL:
    Value: !Sub "https://${StaticWebsiteBucket.DomainName}"
    Description: Secure URL of S3 bucket to hold static website content
    Export:
      Name:
        Fn::Sub: "${AWS::StackName}-S3BucketSecureURL"
  S3BucketName:
    Value:
      Fn::Select:
        - 0
        - Fn::Split: [".", !GetAtt StaticWebsiteBucket.DomainName]
    Description: Name of S3 bucket to hold static website content
    Export:
      Name:
        Fn::Sub: "${AWS::StackName}-S3BucketName"
