AWSTemplateFormatVersion: "2010-09-09"
Description: CloudFormation template to create a ACM certificate

Parameters:
  DomainName:
    Type: String
    Description: domain name
  HostedZoneId:
    Type: String
    Description: HostedZone Id

Resources:
  Certificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: !Ref DomainName
      ValidationMethod: DNS
      DomainValidationOptions:
        - DomainName: !Ref DomainName
          HostedZoneId: !Ref HostedZoneId
      Tags:
        - Key: "Purpose"
          Value: "Asm3"

Outputs:
  CertificateArn:
    Description: The ARN of the ACM Certificate
    Value: !Ref Certificate
